name: Deploy to dev
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select a branch to deploy'
        required: true
        default: 'dev'
      

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
       
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Install dependencies
        run: npm install
      - name: list before build
        run: ls -al
      - name: Build app
        run: npm run build
      - name: list after build
        run: ls -al
      - name: list inside build
        run: ls ./build
      - name: Run tests
        run: npm test
      - name: list after lest
        run: ls -al
        
  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Set up SSH connection
        uses: webfactory/ssh-agent@v0.5.0
        with:
         ssh-private-key: ${{ secrets.EC2_KEY }}
      - name: Delete previous build
        run: ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "rm -rf /var/myapp/"
      - name: Copy files to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
          source: ./build/
          target: "/var/myapp"
      - name: List files on EC2
        run: ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "ls -al /var/myapp"
     
         